name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.103
    - name: Build Application with dotnet 2.2.103
      run: dotnet build --configuration Release
    - name: Run Tests
      run: dotnet test --verbosity normal
