name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build Application with dotnet 3.1.100
      run: dotnet build Paymongo --configuration Release
    - name: Run Tests
      run: dotnet test Paymongo --verbosity normal
